/// Generated by AssetsRefGenerator on 2022/03/10
// ignore_for_file: constant_identifier_names

class Res {
  static const String afaq_logo = "assets/images/afaq-logo.png";
  static const String Cloudy = "assets/images/Cloudy.png";
  static const String Night = "assets/images/Night.png";
  static const String Rainy = "assets/images/Rainy.png";
  static const String Sunny = "assets/images/Sunny.png";
}
